# Workflow name
name: Hello World
# Event triggered can determined as array test1,test2
on: 
  push:
    branches: [main]
    paths-ignore: ".github/workflows/*"
    # paths: ".github/workflows/*"  included path for triggered workflows
    # push: [a, b] 
    # = 
    # push: 
    #   -a 
    #   -b

  # When pull request has been requested to main branch
  pull_request:
    branches: [main]
    
  # Determine external event listener
  # External systems will have to send HTTP Request with event types to github
  # then github will listen with workflow_dispatch event
  repository_dispatch: 
    types: ["on-demand-test"]
        
# List jobs
jobs:
  # Job name
  hello-job:
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello Github Actions!"
  second-job:
    runs-on: windows-latest
    # Add synchro jobs (Means the second job will not executed unitil needs jobs are not done)
    # If not set all jobs will run asynchronous which means all jobs will run parallel with independent to each others
    needs: hello-job
    steps:
      - name: Run a one-line script
        run: echo "Runs jobs on environ ${{ runner.os }}"

        
