# Workflow name
name: Hello World

# ${{}} is used for express github action variables (context variables)
# "$APP_VERSION" is ubuntu shell variable forma

# Determine custom environment variables for all jobs used with every jobs server runner
# Github actions provided build-in env var but you can determine by your seld
env:
  APP_NAME: "Demo Application"

# Event triggered can determined as array test1,test2
on: 
  push:
    branches: [main]
    paths-ignore: ".github/workflows/*"
    # paths: ".github/workflows/*"  included path for triggered workflows
    # push: [a, b] 
    # = 
    # push: 
    #   -a 
    #   -b

  # When pull request has been requested to main branch
  pull_request:
    branches: [main]
    
  # Determine external event listener
  # External systems will have to send HTTP Request with event types to github
  # then github will listen with workflow_dispatch event
  repository_dispatch: 
    types: ["on-demand-test"]
        
# List jobs
jobs:
  echos-var:
    env:
      PACKAGE_PATH: '.'
    runs-on: ubuntu-latest
    steps:
      - name: Echo Github Variable
        env:
          APP_VERSION: "2.34.5"
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: 
          echo "This is event ${ github.event_name }"
          echo "This job trigger by ${{ github.event_name }}"
          echo "This repository is ${{ github.repository }}"
          echo "This branch is ${{ github.ref_name }}"
          echo "This is a ${{ env.APP_NAME }} version ${{ env.APP_VERSION }}"
          echo "$APP_VERSION"
          echo "$RUNNER_CONTEXT"
          echo "The Database password is ${{ secrets.DB_PASSWORD }}"
          
  hello-job:
    if: $${{ github.event_type != 'repository_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: Run a one-line script
        run: echo "Hello Github Actions!"
      - name: Retreve client payload
        run: echo "Client send status ${{ github.event.client_payload.status }}"
  second-job:
    # If condition met it will be executed otherwise it skip
    if: $${{ github.event_type != 'repository_dispatch' }}
    runs-on: windows-latest
    # Add synchro jobs (Means the second job will not executed unitil needs jobs are not done)
    # If not set all jobs will run asynchronous which means all jobs will run parallel with independent to each others
    needs: hello-job
    steps:
      - name: Run a one-line script
        run: echo "Runs jobs on environ ${{ runner.os }}"
        if: $${{ runner.os == 'linux' }}

        
