on: 
  # Manually trigger flow event
  workflow_dispatch:
    # Input argumeny to this workflow (For example there are two arguments: environment, run_ui_test)
    inputs:
      environment: 
        description: 'Target Environment'
        required: true
        type: choice
        options:
          - "Staging"
          - "Production"
      run_ui_test:
        description: 'Run UI Testing'
        required: true
        type: boolean
        default: false
jobs:
  builds:
    runs-on: ubuntu-latest
    # Can be referenced to 'GITHUB_OUTPUT' context
    outputs:
      build_status: ${{ steps.set-status.outputs.status }}
    steps:
      - name: Checkout source code
        # Determine new external action
        uses: actions/checkout@v7.0.0
        # Action's input argument determination
        with:
          repository: ${{ github.repository }}
          # Branch to be checkout to
          ref: ${{ github.ref_name }}
      - name: List files in workspaces
        # List all file on default directory of repository
        run: ls ${{ github.workspace }}
      - name: Set an output status
        id: set-status
        # Get output status and set to GITHUB_OUTPUT
        run: |
          echo "Get result from building proccess"
          echo "status=success" >> $GITHUB_OUTPUT  
  test:
    needs: builds
    runs-on: ubuntu-latest
    steps:
      - name: UI Testing
        if: ${{ inputs.run_ui_test }}
        # Can get output from previous job with 'needs.<job_name>.outputs.<output_variable_name>' context variable
        run: |
          echo "The build status is ${{ needs.builds.outputs.build_status }}"
          echo "Run UI Testing tools in ${{ inputs.environment }} environment"
